[Settings]
  ID = "e7acea3d-94a2-4e8b-b74f-59b4361a574e"

[build]  
  command = "echo \"building\""
  functions = "functions"
  publish = "site"

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
